### ISSUE TITLE
diagram is cut off

### ISSUE THREAD

**Issue by mheiber** [markushedvall/node-plantuml#14]
<img width="105" alt="screen shot 2016-12-21 at 2 42 38 pm" src="https://cloud.githubusercontent.com/assets/4691093/21403651/c4bb82d0-c78b-11e6-981c-94a212e31330.png">

I'm working with a large number of large classes, and the diagrams are cut off (attachment above). The effect is the same whether I export to PNG.

Thanks for your work on this great library! Is there anything you'd recommend in order to get images that are not cut off? Is there a way to export to PDF?

**Comment by markushedvall** [comment]
It would be great if someone could provide me with Plantuml diagram code for reproducing this issue.

**Comment by markushedvall** [comment]
But since this issue is old, and my guess is it was caused by Plantuml I will lose this.

Please reopen if this is still an issue.
