### ISSUE TITLE
Error on Install starting 6/19/18

### ISSUE THREAD

**Issue by toddpi314** [markushedvall/node-plantuml#19]
On node v8.9.4 and npm 5.6.0:

``` shell
npm install node-plantuml@0.6.2

> node-plantuml@0.6.2 postinstall xxx/node_modules/node-plantuml
> node scripts/get-plantuml-jar.js

Downloading plantuml.jar version 1.2018.2
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TLSWrap.onread (net.js:615:25)

```

**Comment by fsmithroku** [comment]
I also see this with node 6.11.0 and npm 3.10.10.  Could plantuml.jar be added to source control, so that it doesn't have to be downloaded from sourceforge.net upon every run?

**Comment by fsmithroku** [comment]
This issue went away within the last week.  At runtime, node-plantuml tries to download plantuml.jar from sourceforge.net.  sourceforge.net was rejecting requests for the download, but is no longer rejecting.  So 0.6.2 is working again for me.
