### ISSUE TITLE
access to sourceforge.net:443 required during install

### ISSUE THREAD

**Issue by PascalPflaum** [markushedvall/node-plantuml#20]
Hi.

Unfortunately the package does only install, when access to sourceforge is available.
In many build/CI systems access to the internet is heavily restricted for security reasons.

It would be nice, if the npm package could be installed without a dependency to a third party website.

**Comment by markushedvall** [comment]
Thanks for reporting.

Now plantuml is downloaded in the postinstall script. Probably it is be better to do it in the prepublish script, so it is published together with the npm package.

I'll look into it.

**Comment by markushedvall** [comment]
This should be solved in v0.7.0. Tell me if you could verify.

**Comment by PascalPflaum** [comment]
Thanks!

I can verify, that during install there is no request to sourceforge.
