### ISSUE TITLE
Should use viz.js when graphviz is not installed

### ISSUE THREAD

**Issue by atifsyedali** [markushedvall/node-plantuml#25]
A lot of npm users would benefit by just doing an `npm install node-plantuml` without having to worry having graphviz installed on their system. Currently, there is a way to do this by using viz.js, which is graphviz compiled using emscripten, and then wrapping that inside a jar by executing with V8. This sounds convoluted but it works well. See http://plantuml.com/vizjs

**Comment by markushedvall** [comment]
Yes, I have been planning to try it out at some point as graphviz installation is a bit painful to have as a dependency. Thanks for your interest in this and I would really like to able to add it as a feature.
