### ISSUE TITLE
Support for the new preprocessor

### ISSUE THREAD

**Issue by marcortw** [markushedvall/node-plantuml#30]
Plantuml released the V2 preprocessor on [the 24th of May this year](http://plantuml.com/news). Do you have any plans on supporting the new preprocessor in the near future?

Currently, when I try out the 'Variable definition' sample from [here](http://plantuml.com/preprocessing), I get the following error plotted in the SVG file:
```
[From string (line 2) ]
@startuml
!$ab = "foo1"
Syntax Error?
```

Kind regards,
Marco

**Comment by markushedvall** [comment]
This will be added when https://github.com/markushedvall/node-plantuml/pull/29 is merged.
I've just been slow keeping up up with new releases of Plantuml.

**Comment by markushedvall** [comment]
This should now be working in the 0.9.0 release.

**Comment by marcortw** [comment]
It works, thanks for the quick response and release of the new version.
