### ISSUE TITLE
Nailgun problem

### ISSUE THREAD

**Issue by petrockblog** [markushedvall/node-plantuml#4]
When I run the example code

``` javascript
var express = require('express');
var plantuml = require('node-plantuml');

var app = express();

plantuml.useNailgun(); // Activate the usage of Nailgun 

app.get('/png/:uml', function(req, res) {
  res.set('Content-Type', 'image/png');

  var decode = plantuml.decode(req.params.uml);
  var gen = plantuml.generate({format: 'png'});

  decode.out.pipe(gen.in);
  gen.out.pipe(res);
});

app.listen(8080);
```

and open the URL `http://localhost:8080/png/UDfpLD2rKt0200GS0Iy0` nothing happens. If I comment out the line `plantuml.useNailgun();` the diagram image is created as expected. `node -v` yields `v0.12.2` for my installation.

I used node-inspector to step through the plantuml-executor functions, but I realized that I am not sure were to specifically look at. Could you give me a direction where to look at or what I could check? .

**Comment by markushedvall** [comment]
Thanks for informing me about this issue.

Actually it seems I have the same problem when I try to reproduce it. It seems something has been changed/broken when using nailgun.

I'll look into it and keep you informed.

**Comment by petrockblog** [comment]
Great, thanks!

**Comment by markushedvall** [comment]
There was a problem with the nails used for nailgun, where the nail for decoding was blocking the nail generating the diagram. This should be fixed now in the 0.4.3 release.

Tell me how it works for you with the new release.

**Comment by petrockblog** [comment]
I tested the 0.4.3 release and things are working now! I am impressed about the decreased processing time - thanks a lot for the quick reply! 

If you are interested, you can see node-plantuml with railgun usage in action at http://www.texwriting.com/uml/new.

**Comment by markushedvall** [comment]
I'm happy it's working fine for you. Thanks for showing me, It's nice to see it in action!
