### ISSUE TITLE
Generating DOT diagrams

### ISSUE THREAD

**Issue by petrockblog** [markushedvall/node-plantuml#5]
I tried to generate a DOT diagram as described at http://de.plantuml.com/dot.html with node-plantuml, for example

```
@startdot
digraph foo {
  node [style=rounded]
  node1 [shape=box]
  node2 [fillcolor=yellow, style="rounded,filled", shape=diamond]
  node3 [shape=record, label="{ a | b | c }"]

  node1 -> node2 -> node3
}
@enddot
```

It only generates a black box, see https://www.texwriting.com/uml/63d9febe6c0229ccc989cf7cf9bb0f32. Could you point me into a promising direction where to look at to make this working? Could it be because of the @startdot and @enddot directives?

**Comment by markushedvall** [comment]
I was looking at your example, and I don't see the black box. For me it rendered half of the diagram. However if I follow the direct link to the diagram: https://www.texwriting.com/api/v1/uml/get/png/6c8574ae4d95b2de65e2587317fd3db5?1450901945727
it loads perfectly.

This shouldn't be an issue of node-plantuml, and should work as long as you are generating to png but I could be wrong.

Do you still not see the diagram?

**Comment by petrockblog** [comment]
Ups, you are right - thanks a lot! node-plantuml is working correctly here as well. Thanks for pointing me to that!
